apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
  namespace: my-namespace
spec:
  containers:
    - name: app-container
      image: nginx:latest
      env:
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:   #configMapKeyRef for configmap
              name: my-secret
              key: username
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
      volumeMounts:
        - name: secret-volume
          mountPath: "/secrets"
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
