apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
spec:
  containers:
    - name: app-container
      image: nginx:latest
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: database-url
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: api-key