apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    certificate-authority-data: <base64-encoded-ca-certificate>
    server: https://cluster-api-server-url:port
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
    namespace: my-namespace
current-context: my-context
users:
- name: my-user
  user:
    client-certificate-data: <base64-encoded-client-certificate>
    client-key-data: <base64-encoded-client-key>
