apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system

spec:
  selector:
    matchLabels:
      app: elasticsearch-app
  template:
    metadata:
      labels:
        app: elasticsearch-app
    spec:
      containers:
      - name: fluentd
        image: registry.k8s.io/fluentd-elasticsearch:1.20