apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
data:
  .dockerconfigjson: |
    {
      "auths": {
        "<your-registry>": {
          "username": "<your-username>",
          "password": "<your-password>",
          "email": "you@example.com"
        }
      }
    }
