apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding
subjects:
- kind: User  # You can use 'ServiceAccount' or 'Group' here if needed
  name: your-username  # Replace with the username, service account, or group name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-role-yaml  # Replace with the name of the ClusterRole
  apiGroup: rbac.authorization.k8s.io
